version: 2
jobs:
  build:
    working_directory: ~/digital_ocean
    docker:
      - image: prorahul/symfony:latest
        environment:
          MAX_EXECUTION_TIME: 60

    steps:
      - checkout

