version: 2
jobs:
  build:
    working_directory: /var/www/symfony
    docker:
      - image: docker:17.05.0-ce-git



    steps:
      - checkout
      - setup_remote_docker
   # docker_layer_caching: true

      - run:
          name: Install Docker Compose
          command: |
             apk add --no-cache \
             py-pip=9.0.0-r1
             pip install \
             docker-compose==1.18.0

      - run:
          name: Run container
          command: |
              docker-compose -f ./docker-compose.yml up -d --build

      - run:
         name: check git version
         command: git --version

      - run:
         name: run php container
         command: |
            docker exec -it container_phpfpm bash
            composer install -n --prefer-dist









