version: 2
jobs:
  build:
    working_directory: /var/www/symfony
    docker:
      - image: docker:17.05.0-ce-git



    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
             apk add --no-cache \
             py-pip=9.0.0-r1
             pip install \
             docker-compose==1.18.0

      - run:
          name: check docker compose version
          command: docker-compose --version

      - run:
          name: Run container
          command: |
          SYMFONY_APP_PATH=./symfony TIMEZONE=Asia/Kolkata MAX_EXECUTION_TIME=60 MYSQL_ROOT_PASSWORD=root \
          MYSQL_DATABASE=symfony  MYSQL_USER=symfony MYSQL_PASSWORD=symfony RABBITMQ_USER=rabbit RABBITMQ_PASSWORD=mq \
          docker-compose -f ./docker-compose.yml up -d --build