version: 2
jobs:
  build:
    working_directory: /var/www/symfony
    docker:
      - image: docker:17.05.0-ce-git



    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
             apk add --no-cache \
             py-pip=9.0.0-r1
             pip install \
             docker-compose==1.18.0

      - run:
          name: check docker compose version
          command: docker-compose --version

      - run:
          name: Run container
          command: |
          SYMFONY_APP_PATH=./symfony docker-compose -f ./docker-compose.yml up -d --build