version: 2
jobs:
  build:
    working_directory: ~/digital_ocean
    docker:
      - image: prorahul/symfony:latest

    steps:
      - checkout
      - run:
          name: Hello world
          command: echo "hello world"

