version: 2
jobs:
  build:
    working_directory: ~/digital_ocean
    docker:
    - image: prorahul/symfony:nginx
    - image: prorahul/symfony:php

    steps:
      - checkout

      - run:
          name: check nginx version
          command: nginx -v

