version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.bashrc"
    working_directory: /var/www/symfony
    docker:
      - image: docker:17.05.0-ce-git



    steps:
      - checkout
      - setup_remote_docker
   # docker_layer_caching: true

      - run:
          name: Install Docker Compose
          command: |
             apk add --no-cache \
             py-pip=9.0.0-r1
             pip install \
             docker-compose==1.18.0

      - run:
          name: Run container
          command: |
              docker-compose -f ./docker-compose.yml up -d --build

      - run:
         name: check git version
         command: git --version
      - run:
         name: install composer
         command: |
             cd /tmp
             EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
             php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
             ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
             if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
             then
                 >&2 echo 'ERROR: Invalid installer signature'
                 rm composer-setup.php
                 exit 1
             fi
             sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
             RESULT=$?
             rm composer-setup.php
             exit $RESULT
      - run:
         name: composer install
         command: composer install





