version: 2
jobs:
  build:
    working_directory: ~/symfony
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
   # docker_layer_caching: true

      - run:
          name: Install Docker Compose
          command: |
             apk add --no-cache \
             py-pip=9.0.0-r1
             pip install \
             docker-compose==1.18.0

      - run:
          name: Run container
          command: |
              docker-compose -f ./docker-compose-test.yml up -d --build

      - run:
         name: mount volume
         command: docker cp ./symfony container_phpfpm:/var/www/

      - run:
         name: install composer
         command: |
            docker exec container_phpfpm composer install -n --prefer-dist

      - run:
          name: Run migrations
          command: docker exec container_phpfpm bin/console doctrine:migrations:migrate --env=test --no-interaction

      - run:
         name: Run Test
         command: docker exec container_phpfpm ./bin/phpunit


  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout

    - run:
         name: add droplet
         command: ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts

      - run:
         name: add env variable
         command: ssh -T $DROPLET_USER@$DROPLET_IP < ./symfony/bin/deploy/pre_deploy.sh

#      - run:
#          name: Run container
#          command: |
#              docker-compose -f ./docker-compose.yml up -d --build
#
#      - run:
#         name: mount volume
#         command: docker cp ./symfony container_phpfpm:/var/www/
#
#      - run:
#         name: install composer
#         command: |
#            docker exec container_phpfpm composer install -n --prefer-dist
#
#      - run:
#         name: clear cache
#         command: docker exec container_phpfpm bin/console cache:clear --env=prod --no-interaction
#
#      - run:
#         name: warmup cache
#         command: docker exec container_phpfpm bin/console cache:warmup --env=prod --no-interaction
#
#      - run:
#         name: yarn error
#         command: docker exec container_phpfpm yarn config set ignore-engines true
#
#      - run:
#         name: yarn
#         command: docker exec container_phpfpm yarn install
#
#      - run:
#         name: run encore
#         command: docker exec container_phpfpm yarn run encore production
#
#      - run:
#         name: run migrations
#         command: docker exec -e DATABASE_URL=$DATABASE_URL  container_phpfpm bin/console doctrine:migrations:migrate --no-interaction


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy









