version: 2
jobs:
  build:
    working_directory: ~/digital_ocean
    docker:

    - image: prorahul/symfony:php

    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony

    steps:
      - checkout
      - run:
          name: install nginx
          command: apt-get update && apt-get install -y nginx

      - run:
          name: add conf file
          command: cp nginx.conf /etc/nginx/

      - run:
          name: add symfony conf
          command: cp symfony.conf /etc/nginx/sites-available/




